### PR TITLE
Gh-304: Build images script doesn't expose environment variables correctly

### LINKED ISSUE #304: Publish images script doesn't expose environment variables correctly
In [publish_images.sh there's a new section](https://github.com/gchq/gaffer-docker/blob/72fb892abc9eaf5219d6d002cb80b7e6791a9c3e/cd/publish_images.sh#L115) for sourcing particular versions of Hadoop, Accumulo etc. This doesn't work as intended because the environment variables are not exported, therefore they are not passed to the `docker compose` process and don't override the `.env` file which is the intention.

### PR DESCRIPTION
**Pull request by GCHQDeveloper314**
# Related Issue

- Resolve #304

### CODE REVIEW

File: cd/build_images.sh [hunk 1]
```diff
@@ -14,7 +14,9 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-set -e
+# -a: Always export variables to subsequent commands.
+# Required for variables from sourced env file to automatically be visible to docker compose.
+set -e -a
```
Comment (t92549) [inline cd/build_images.sh:19]: Does this also need to happen in `publish_images.sh`? Or even everything in the `cd` directory?

Comment (GCHQDeveloper314) [reply cd/build_images.sh:19]: No. In `publish_images.sh` the variables are only used within the script and not by any child processes. Same for the others. It's just `docker compose` which uses/needs them, and only since the change to use legacy images.

**Review by t92549 — APPROVED** [review]
