### PR TITLE
Gh-231: Add new scripts for checking copyright headers

### LINKED ISSUE #231: Improve process for updating copyright headers
At the moment there are no automatic checks to ensure that copyright dates are updated when a file is modified. Instead there's a reliance on checking this as part of code review. This approach has resulted in copyright dates becoming wrong.

There are some existing scripts which need to be run manually. However, these do not update headers correctly in all cases and are not suitable for automatic running by GitHub Actions CI.

The existing scripts should be replaced so that copyright dates can be checked as part of GitHub Actions CI. This removes any need for manual checks during code review.

### PR DESCRIPTION
**Pull request by GCHQDeveloper314**
Script to check and one to fix. Use check script in CI.

# Related Issue

- Resolve #231

### CODE REVIEW

File: cd/fix_copyright_headers.sh [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+        error=true
+      fi
+    fi
+  done
+else
+  echo "Empty Diff"
+  exit 1
+fi
+
+# Return error code if changes are needed (used by CI)
```
Comment (t92549) [inline cd/fix_copyright_headers.sh:58]: Very small detail but this script isn't used by the CI

File: cd/fix_copyright_headers.sh [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+        if [ -n "$dateRange" ]
+        then
+          sed -E -i '' -e "s/^(.*Copyright )(....)-(....)(.*)$/\1\2-$currentYear\4/g" $modifiedFile
+        else
+          sed -E -i '' -e "s/^(.*Copyright )(....)(.*)$/\1\2-$currentYear\3/g" $modifiedFile
+        fi
+        echo "Updated Copyright Header in '$modifiedFile'"
+      elif [ -n "$fileNeedsHeader" ] && [ -z "$currentHeader" ] # If header is required but doesn't exist
+      then
+        echo "Missing any Copyright Header in '$modifiedFile', must be added manually"
```
Comment (t92549) [inline cd/fix_copyright_headers.sh:48]: Would it be possible to add automatically? By providing a template for what the header should look like, similar to what spotless does?

**Review by t92549 — APPROVED** [review]
